### ISSUE TITLE
how to use dynamic token in api testing.

### ISSUE THREAD

**Issue by shanthkumar043** [akshayp7/playwright-typescipt-playwright-test#23]
![image](https://user-images.githubusercontent.com/52404918/159501490-4277f397-d6d5-4426-8522-63f43cd6244a.png)

Please refer this screen shot

**Comment by akshayp7** [comment]
You can refer below article for using tokens in Playwright. I feel currently they only support static tokens.
By the way you can use Post Request to get the token and store it in a variable in User it in tests, I haven't implemented it though

https://playwright.dev/docs/test-api-testing

**Comment by akshayp7** [comment]
You can try the below code as well, its implemented in puppeteer with tweaking it might work for playwright

https://stackoverflow.com/questions/70595609/code-way-for-creating-a-authorization-code-jwt-token

**Comment by shanthkumar043** [comment]
Thanks Akshay ...
